kind: Service
apiVersion: v1
metadata:
  name: vuejs-frontend
spec:
  selector:
    app: {{ template "fullname" . }}
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
  type: ClusterIP
